# This workflow automates setup, dependency installation with cache, build, and test processes for Node.js 20.x on PR events (open, reopen, sync).
# See: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Development Workflow

on:
  push:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'npm'
      - name: Install dependencies
        run: npm install
      - name: Build project
        run: npm run build
      - name: Run tests
        run: npm test
